// Additional illustrative records use topic names from the captured Uplift workspace.
const additional = [
  [
    "Buffet vs. boxed lunches: which fits your office?",
    "SEO article",
    "Sep 2, 2026",
    "Published",
    "peach",
    140,
  ],
  [
    "The benefits of individually packaged meals",
    "SEO article",
    "Sep 3, 2026",
    "Published",
    "green",
    90,
  ],
  [
    "7 menu planning choices for your next meeting",
    "SEO article",
    "Sep 4, 2026",
    "Published",
    "purple",
    110,
  ],
  [
    "Mexican-inspired office lunches",
    "Social post",
    "Sep 7, 2026",
    "Published",
    "peach",
    0,
  ],
  [
    "Mediterranean flavors for teams",
    "Social post",
    "Sep 8, 2026",
    "Published",
    "blue",
    0,
  ],
  [
    "Healthy salad catering guide",
    "SEO article",
    "Sep 9, 2026",
    "Published",
    "green",
    480,
  ],
  [
    "When to choose buffet-style office catering",
    "Social post",
    "Sep 11, 2026",
    "Published",
    "purple",
    0,
  ],
  [
    "Office snack delivery",
    "SEO article",
    "Sep 21, 2026",
    "Draft",
    "peach",
    900,
  ],
  [
    "Breakfast catering for corporate meetings",
    "SEO article",
    "Sep 22, 2026",
    "Ready for review",
    "blue",
    160,
  ],
  [
    "A corporate catering checklist",
    "SEO article",
    "Sep 23, 2026",
    "Draft",
    "green",
    120,
  ],
  [
    "Recurring office meal programs",
    "Social post",
    "Sep 25, 2026",
    "Draft",
    "purple",
    0,
  ],
  [
    "Dietary restriction catering guide",
    "SEO article",
    "Sep 28, 2026",
    "Ready for review",
    "blue",
    100,
  ],
];
export const extraContent = additional.map(
  ([title, type, date, status, tone, volume], index) => ({
    id: index + 7,
    title,
    type,
    date,
    status,
    tone,
    volume,
    time: type === "Social post" ? "02:00 PM" : "08:00 AM",
    keyword: title.toLowerCase().replace(/[?:]/g, ""),
    description: `A ${type === "Social post" ? "social content set" : "content preview"} for LunchLink covering ${title.toLowerCase().replace(/[?]/g, "")}. Review the topic, target keyword, and publishing date before scheduling.`,
    illustrative: true,
  }),
);
