export const content = [
  {
    id: 1,
    title: "Allergen labeling best practices",
    type: "SEO article",
    date: "Sep 14, 2026",
    time: "08:00 AM",
    status: "Scheduled",
    tone: "peach",
    keyword: "allergen labeling best practices",
    volume: 50,
    description:
      "A practical guide to clear allergen labeling for corporate catering, with steps to help teams communicate dietary information.",
  },
  {
    id: 2,
    title: "Halal menu compliance",
    type: "SEO article",
    date: "Sep 15, 2026",
    time: "08:00 AM",
    status: "Scheduled",
    tone: "purple",
    keyword: "halal menu compliance",
    volume: 40,
    description:
      "Plan a halal-friendly office menu and communicate requirements clearly with your catering provider.",
  },
  {
    id: 3,
    title: "Vegan office catering options",
    type: "SEO article",
    date: "Sep 16, 2026",
    time: "08:00 AM",
    status: "Scheduled",
    tone: "green",
    keyword: "vegan office catering options",
    volume: 70,
    description:
      "Explore plant-based catering options for office lunches, meetings, and team events.",
  },
  {
    id: 4,
    title: "Gluten-free catering strategies",
    type: "SEO article",
    date: "Sep 17, 2026",
    time: "08:00 AM",
    status: "Draft",
    tone: "blue",
    keyword: "gluten-free catering strategies",
    volume: 60,
    description:
      "Build a more inclusive office catering plan with clearly identified gluten-free menu options.",
  },
  {
    id: 5,
    title: "Corporate catering across the GTA",
    type: "Social post",
    date: "Sep 18, 2026",
    time: "02:00 PM",
    status: "Ready for review",
    tone: "peach",
    keyword: "corporate catering GTA",
    volume: 120,
    description:
      "A coordinated content set introducing what LunchLink delivers to workplaces across the Greater Toronto Area.",
  },
  {
    id: 6,
    title: "Individually packaged meals for meetings",
    type: "Social post",
    date: "Sep 19, 2026",
    time: "02:00 PM",
    status: "Ready for review",
    tone: "purple",
    keyword: "individually packaged meals benefits",
    volume: 90,
    description:
      "A social content set covering convenient individually packaged meals for workplace meetings.",
  },
];